@echo off
vcredist_x86.exe
mkdir "C:\Program Files\CactaiGotchi"
copy CactaiGotchi.exe "C:\Program Files\CactaiGotchi"
copy openal32.dll "C:\Program Files\CactaiGotchi"
copy OpenSans.ttf "C:\Program Files\CactaiGotchi"
copy sfml-audio-2.dll "C:\Program Files\CactaiGotchi"
copy sfml-graphics-2.dll "C:\Program Files\CactaiGotchi"
copy sfml-network-2.dll "C:\Program Files\CactaiGotchi"
copy sfml-system-2.dll "C:\Program Files\CactaiGotchi"
copy sfml-window-2.dll "C:\Program Files\CactaiGotchi"
mkdir "C:\Program Files\CactaiGotchi\img"
copy img\back.png "C:\Program Files\CactaiGotchi\img"
copy img\cactaifood.png "C:\Program Files\CactaiGotchi\img"
copy img\cactstill1grey.png "C:\Program Files\CactaiGotchi\img"
copy img\cactstill2grey.png "C:\Program Files\CactaiGotchi\img"
copy img\dripping-honey.png "C:\Program Files\CactaiGotchi\img"
copy img\droplets.png "C:\Program Files\CactaiGotchi\img"
copy img\flame.png "C:\Program Files\CactaiGotchi\img"
copy img\fluffy-cloud.png "C:\Program Files\CactaiGotchi\img"
copy img\gameover.png "C:\Program Files\CactaiGotchi\img"
copy img\howto.png "C:\Program Files\CactaiGotchi\img"
copy img\title.png "C:\Program Files\CactaiGotchi\img"